### ISSUE TITLE
nie działają

### ISSUE THREAD

**Issue by arek11x** [streambase-project/index#123]
nie działają przynajmniej mi :)
https://rinzry.stream/
https://anime-maou.pl/
https://123anime.to/
https://0dayhome.net/
hugewarez.net
https://jackfreakz.com
https://uhdmv.org/
https://rarbg.to
https://proxybay.github.io/
https://ibit.to/
https://crackx.to/
https://myoplay.club/
http://crackstreams.net/
https://nbafullhd.com/
https://xaudiobooks.com/
https://largepdf.net/
https://www.16bit.pl/
https://repack-games.cc/
https://media.mp3-malina.me/
https://alldj.org/
https://snapdrop.net/

**Comment by streambase-project** [comment]
@arek11x @TestNintendo dziękujemy za zgłoszenie, będziemy to usuwać w najbliższym czasie.

**Comment by Wardzislaw** [comment]
Działa już:
- https://16bit.pl/
- https://snapdrop.net/
- https://0dayhome.net/

**Comment by streambase-project** [comment]
Będę edytował tę wiadomość na bieżąco.
https://rinzry.stream/ - usunięte.
https://anime-maou.pl/
https://123anime.to/
https://0dayhome.net/
https://hugewarez.net
https://jackfreakz.com/
https://uhdmv.org/
https://rarbg.to/
https://proxybay.github.io/
https://ibit.to/
https://crackx.to/
https://myoplay.club/
http://crackstreams.net/
https://nbafullhd.com/
https://xaudiobooks.com/
https://largepdf.net/
https://www.16bit.pl/
https://repack-games.cc/
https://media.mp3-malina.me/
https://alldj.org/
https://snapdrop.net/
