### ISSUE TITLE
nie działają 2-kolejna dawka 

### ISSUE THREAD

**Issue by arek11x** [streambase-project/index#149]
powoli się serial z tego zrobi 

https://esspc-ebooks.com/ - Przekroczono limi czasu połączenia 
https://starlive.xyz/ - Przekroczono limi czasu połączenia 
https://mamahd.best/ - Niestety, nie udało się odnaleźć tej strony
http://ww1.hdtshare.com/ - pusta strona 
https://super-warez.eu/ - 404 Упс! Мы не можем найти страницу, которую вы ищете. Oops! We can not find the page you are looking for. Попробуйте поискать на главной. 
https://mynavi-expert.pl/- wyświetla się tylko webserver is functioning normally 
https://foogle.shivamhw.me/ - 502 Bad gateway
https://zoro.to/ - Niestety, nie udało się odnaleźć tej strony
https://gogoanime.llc/ - Niestety, nie udało się odnaleźć tej strony
https://grupahatak.pl/ - 522 Connection timed out
https://s2dfree.cc/ - Hello guys: We have decided to close soap2day forever. We are very sorry :) Bye
https://playz.cc/ - 503 Service Temporarily Unavailable

**Comment by streambase-project** [comment]
@arek11x 

> powoli się serial z tego zrobi

Taki ten świat jest, że wiele stron pada, wkrótce będziemy przeglądać i usuwać.

**Comment by streambase-project** [comment]
Będziemy edytować to na bieżąco:
https://esspc-ebooks.com/ 
https://starlive.xyz/ 
https://mamahd.best/ 
http://ww1.hdtshare.com/
https://super-warez.eu/ 
https://mynavi-expert.pl/
https://foogle.shivamhw.me/
https://zoro.to/
https://gogoanime.llc/
https://grupahatak.pl/
https://s2dfree.cc/ 
https://playz.cc/
