### ISSUE TITLE
nie działają 3-trylogia

### ISSUE THREAD

**Issue by arek11x** [streambase-project/index#157]
https://trailers.to/ - Connection timed out
http://ww38.gomovie.sc/ - 
https://filmeria.co/ - Nie udało się nawiązać połączenia
https://filevids.cc/ - Niestety, nie udało się odnaleźć tej strony
https://animedao.to/ - Shutting down
We can't provide content anymore without popup-ads. All the scraped contents are protected by cors or other security measures.
This domain is also being targeted and we don't want to change domains.
If you have bookmarks. 
animedao.to is the only animedao domain. The others claiming to be us are fake.
Thank you and goodbye~
https://ww7.extratorrent.cyou/ - Przekroczono limit czasu połączenia,
https://prostylex.org/ - Przekroczono limit czasu połączenia, This domain (prostylex.org) expired on 19/07/2023. You can retrieve your domain
https://torrentz2.pics/beta2/ - 
https://www.btsearch.ml/ - Niestety, nie udało się odnaleźć tej strony

**Comment by Wardzislaw** [comment]
Kurwa coś dużo stron pada.

**Comment by TestNintendo** [comment]
co do https://www.megastacja.tv/ to musisz użyć VPN-a
dla mnie optymalną lokalizacją jest Szwajcaria

**Comment by arek11x** [comment]
> co do https://www.megastacja.tv/ to musisz użyć VPN-a dla mnie optymalną lokalizacją jest Szwajcaria

ok

**Comment by streambase-project** [comment]
https://trailers.to/
http://ww38.gomovie.sc/ 
https://filmeria.co/ 
https://filevids.cc/ - usunięte.
https://animedao.to/
animedao.to
https://ww7.extratorrent.cyou/
https://prostylex.org/
https://torrentz2.pics/beta2/
https://www.btsearch.ml/
